%YAML:1.0

image_width: 320
image_height: 240
camera_name: gazebo
camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: f
  data: [214.597, 0, 153.9, 0, 214.407, 117.298, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients: !!opencv-matrix
  rows: 1
  cols: 5
  dt: f
  data: [0, 0, 0, 0, 0]
rectification_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: f
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  
 #This needs to be calculated... For now it's useless
projection_matrix: !!opencv-matrix
  rows: 3
  cols: 4
  dt: f
  data: [214.597, 0, 153.9, 0, 0, 214.407, 117.298, 0, 0, 0, 1, 0]
